version: "3.9"
services:

  kaddem:
    container_name: kaddem
    image: kaddem
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8060:8060"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddem\db?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.hibernate.ddl-auto : update
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

    depends_on:
      - mysqldb
    volumes:
      - kaddem:/kaddem
    networks:
      - spring-network



  mysqldb:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_ALLOW_EMPTY_PASSWORD:"yes"
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    restart:  unless-stopped
    volumes:
      - mysql:/mysql
    networks:
      - spring-network

networks:
  - spring-network:
volumes:
  - kaddem:
  - mysql: