version: "3.9"
services:

  app:
    container_name: kaddem-app
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8060:8060"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddem\db?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.show-sql: true
      spring.jpa.hibernate.ddl-auto : update
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect

    depends_on:
      - mysqldb
    networks:
    - spring-network



  mysqldb:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_ALLOW_EMPTY_PASSWORD:"yes"
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    restart:  unless-stopped
    networks:
      - spring-network

networks:
  - spring-network: